# **Разведочный анализ по датасету IMDb Movies: 5000 фильмов с наибольшим рейтингом. Часть 1: Обзор и предобработка данных**

![](https://adabul.com/wp-content/uploads/2020/04/diziler-360x240.jpg)

## 1. Описание датасета и задания

Представлен датасет с данными о 5000 фильмах, имеющих наибольший рейтинг на сайте IMDb (датасет выложен на платформе [Kaggle](https://www.kaggle.com/datasets/totoro29/imdb-movies)).

***Информация, содержащаяся в датасете:***
1.   Ссылка на постер фильма (poster).
2.   Наименование фильма (title).
3.   Класс фильма по рейтингу the British Board of Film Classification (BBFC) (certificate).
4.   Продолжительность фильма (runtime).
5.   Жанр фильма (genre).
6.   Рейтинг фильма на платформе IMBD (rating).
7.   Описание сюжета фильма (about).
8.   Кинорежиссер фильма (director).
9.   Актеры-звезды фильма (stars).
10.  Количество проголосовавших за фильм (votes).
11.  Доход с фильма (gross_earn).

***Задача:***
провести разведочный анализ данных, найти взаимосвязи и сформулировать выводы.

**В части 1 задания необходимо:**
1.   Выполнить обзор данных.
2.   Оценить датасет на наличие дубликатов и при необходимости обработать их.
3.   Оценить признаки на наличие пропусков и при необходимости обработать их.
4.   Привести данные к необходимому для анализа типу.
5.   Отсортировать и сохранить датасет для дальнейшего анализа.

## 2. Загрузка датасета

In [9]:

!pip install --upgrade gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (6.0.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.29.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2026.4.22)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)

In [10]:
!gdown 1SQihqE13h5sEVzLSaBn9f2l_FdMtxNQb -O movies.csv

Downloading...
From: https://drive.google.com/uc?id=1SQihqE13h5sEVzLSaBn9f2l_FdMtxNQb
To: /content/movies.csv
100% 1.89M/1.89M [00:00<00:00, 107MB/s]

## 3. Подгрузка данных в питон и начало работы с ними

In [11]:
import pandas as pd
import numpy as np

In [12]:
dataset = pd.read_csv('movies.csv')

Проведите обзор таблицы с помощью метода head()

In [13]:
dataset.head()

,poster,title,certificate,runtime,genre,rating,about,director,stars,votes,gross_earn
0,https://m.media-amazon.com/images/S/sash/4Fyxw...,The Shawshank Redemption,15,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,"('Tim Robbins',), ('Morgan Freeman',), ('Bob G...","26,26,905",$28.34M
1,https://m.media-amazon.com/images/S/sash/4Fyxw...,The Dark Knight,12A,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Christopher Nolan,"('Christian Bale',), ('Heath Ledger',), ('Aaro...","25,98,173",$534.86M
2,https://m.media-amazon.com/images/S/sash/4Fyxw...,Inception,12A,148 min,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,Christopher Nolan,"('Leonardo DiCaprio',), ('Joseph Gordon-Levitt...","23,04,062",$292.58M
3,https://m.media-amazon.com/images/S/sash/4Fyxw...,Fight Club,18,139 min,Drama,8.8,An insomniac office worker and a devil-may-car...,David Fincher,"('Brad Pitt',), ('Edward Norton',), ('Meat Loa...","20,71,088",$37.03M
4,https://m.media-amazon.com/images/S/sash/4Fyxw...,Pulp Fiction,18,154 min,"Crime, Drama",8.9,"The lives of two mob hitmen, a boxer, a gangst...",Quentin Tarantino,"('John Travolta',), ('Uma Thurman',), ('Samuel...","20,11,013",$107.93M

## 4. Оценка размеров датасета, наличия дубликатов и пропусков

Оценим размеры датасета с помощью атрибута shape

In [14]:
dataset.shape

(5000, 11)

Выведем информацию о датасете с помощью метода info(). Оценим признаки и типы данных, обратим внимание на пропущенные значения

In [15]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   poster       5000 non-null   object
 1   title        5000 non-null   object
 2   certificate  5000 non-null   object
 3   runtime      5000 non-null   object
 4   genre        4970 non-null   object
 5   rating       5000 non-null   float64
 6   about        4986 non-null   object
 7   director     5000 non-null   object
 8   stars        5000 non-null   object
 9   votes        5000 non-null   object
 10  gross_earn   4585 non-null   object
dtypes: float64(1), object(10)
memory usage: 429.8+ KB

Оценим наличие дубликатов в датасете с помощью метода duplicated() в связке с sum() (при необходимости исключим полные дубликаты)

In [16]:
dataset.duplicated().sum()

np.int64(0)

In [17]:
df = dataset.copy()

In [18]:
df.duplicated(subset='title').sum()

np.int64(109)

In [19]:
df.drop_duplicates(subset='title', inplace=True)

In [20]:
dataset.shape

(5000, 11)

Оценим наличие пропущенных значений в датасете по признаку gross_earn

In [21]:
df.duplicated(subset='gross_earn').sum()

np.int64(1563)

P.s. не стоит исключать наблюдения с пропущенными значениями на этапе предобработки датасета, если нет жесткого требования это делать. Так можно потерять информацию по другим более значимым признакам. Кроме того, их наличие может нести ценную информацию при анализе.

**Выводы:**


1.   О размерах датасета (количество признаков и количество наблюдений).
5000, 11
2.   О типах данных (какие есть и какие должны быть, нужна ли предобработа).
rating: float перевести в int
gross_earn: object перевести в int
3.   О дубликатах (их наличие, нужна ли предобработка).
4.   О пропущенных значениях (их наличие, нужна ли предобработка).
в genre, about, gross_earn
5.   О возможных проблемах, которые могут возникнуть при анализе.

## 5. Обработка колонок runtime и gross_earn: приведение к числовому типу

Приведем значения признаков runtime и gross_earn к числовому типу, исключив лишние символы

### *5.1. runtime*

Выведем Series ['runtime'] для детального просмотра данных

In [22]:
dataset['runtime']

0              142 min
1              152 min
2              148 min
3              139 min
4              154 min
             ...
4995           102 min
4996            94 min
4997    Drama, Romance
4998            92 min
4999           120 min
Name: runtime, Length: 5000, dtype: object

По индексу 4997 в признак попало аномальное значение - Drama, Romance

Выведем уникальные значения по Series ['runtime'] с помощью метода unique()

In [23]:
df['runtime'].unique()

array(['142 min', '152 min', '148 min', '139 min', '154 min', '178 min',
       '136 min', '201 min', '175 min', '164 min', '179 min', '127 min',
       '143 min', '155 min', '140 min', '165 min', '169 min', '121 min',
       '118 min', '162 min', '153 min', '151 min', '195 min', '113 min',
       '130 min', '124 min', '122 min', '194 min', '132 min', '202 min',
       '138 min', '119 min', '189 min', '180 min', '137 min', '106 min',
       '111 min', '116 min', '145 min', '110 min', '98 min', '107 min',
       '126 min', '100 min', '131 min', '133 min', '103 min', '108 min',
       '96 min', '99 min', '115 min', '88 min', '120 min', '81 min',
       '135 min', '146 min', '117 min', '104 min', '92 min', '91 min',
       '102 min', '149 min', '170 min', '112 min', '101 min', '141 min',
       '144 min', '114 min', '150 min', '90 min', '161 min', '128 min',
       '93 min', '129 min', '166 min', '147 min', '134 min', '109 min',
       '105 min', '125 min', '156 min', '123 min', '95 min', '157 min',
       '163 min', '158 min', '89 min', '187 min', '167 min', '84 min',
       '94 min', '85 min', '172 min', '160 min', '168 min', '86 min',
       '97 min', '87 min', '183 min', '188 min', '207 min', '159 min',
       '76 min', '229 min', '238 min', '83 min', '218 min', '77 min',
       '181 min', '191 min', '80 min', '212 min', '78 min', '79 min',
       '82 min', '74 min', '185 min', '75 min', '197 min', '69 min',
       '64 min', '224 min', '68 min', '210 min', '177 min', '193 min',
       '67 min', '174 min', '70 min', '220 min', '321 min', 'Comedy',
       '186 min', 'Action, Crime, Mystery', '198 min', '58 min',
       'Comedy, Drama, Romance', 'Comedy, Romance', '192 min', '242 min',
       'Horror', '204 min', 'Comedy, Drama', '171 min', '63 min',
       'Horror, Sci-Fi, Thriller', 'Action, Biography, Drama', '182 min',
       '176 min', '196 min', 'Drama', '205 min', 'Action, Drama, War',
       '71 min', '259 min', '45 min', 'Fantasy, Romance',
       'Action, Crime, Comedy', 'Crime, Drama, Mystery',
       'Action, Adventure, Drama', 'Drama, Horror, Mystery',
       'Crime, Mystery', '213 min', '72 min', '216 min',
       'Comedy, Western', '317 min', 'Adventure, Drama, Romance',
       'Fantasy, Horror', 'Adventure, Comedy', 'Comedy, Family',
       'Adventure, Comedy, Romance', '366 min', 'Action, Comedy',
       'Adventure, Comedy, Fantasy', 'Action, Adventure, Sci-Fi',
       'Drama, Romance'], dtype=object)

Таких аномальных значений несколько. Следует исключить их из датасета

In [24]:
import re

Напишем функцию, которая исключит нецифровые символы с помощью регулярных выражений

In [25]:
import re
import pandas as pd

def clear_runtime(runtime):
    """
    Удаляет все НЕцифровые символы (regex) и возвращает целое число.
    Если после очистки цифр нет — возвращает pd.NA.
    """
    if pd.isna(runtime):
        return pd.NA

    s = str(runtime)
    digits = re.sub(r"\D+", "", s)   # \D = любой НЕ-цифровой символ

    return int(digits) if digits else pd.NA

Примените функцию к Series ['runtime'] с помощью метода apply()

In [26]:
df["runtime_clean"] = df["runtime"].apply(clear_runtime).astype("Int64")

Создадим столбец runtime_clear в исходном датасете, применив функцию к признаку runtime

In [27]:
dataset['runtime_clear'] = dataset["runtime"].apply(clear_runtime).astype("Int64")

Выведем Series ['runtime_clear'] для оценки результата

In [28]:
dataset['runtime_clear']

0        142
1        152
2        148
3        139
4        154
        ...
4995     102
4996      94
4997    <NA>
4998      92
4999     120
Name: runtime_clear, Length: 5000, dtype: Int64

По индексу 4997, где было аномальное значение, теперь на первый взгляд пустота. Проверим, так ли это, с помощью метода isna()

In [29]:
df['runtime_clean'].isna().sum()

np.int64(29)

Количество пустых полей - 0... Посмотрим поближе, что же на самом деле записано в данном поле с помощью индексации датасет['столбец'][индекс]

In [30]:
dataset['runtime_clear'][4997]

Записано нулевое строковое значение. Убедитесь в этом, проверив тип данных с помощью функции type()

In [31]:
dataset['runtime_clear'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 5000 entries, 0 to 4999
Series name: runtime_clear
Non-Null Count  Dtype
--------------  -----
4970 non-null   Int64
dtypes: Int64(1)
memory usage: 44.1 KB

Действительно, это строковое значение. Отфильтруем датасет, исключив все такие значения с помощью оператора !=

In [32]:
dataset = dataset[dataset['runtime_clear']!='']

Оценим размеры датасета с помощью атрибута shape

In [33]:
dataset.shape

(4970, 12)

А также проверим тип данных с помощью метода info()

In [34]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4970 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   poster         4970 non-null   object
 1   title          4970 non-null   object
 2   certificate    4970 non-null   object
 3   runtime        4970 non-null   object
 4   genre          4970 non-null   object
 5   rating         4970 non-null   float64
 6   about          4956 non-null   object
 7   director       4970 non-null   object
 8   stars          4970 non-null   object
 9   votes          4970 non-null   object
 10  gross_earn     4574 non-null   object
 11  runtime_clear  4970 non-null   Int64
dtypes: Int64(1), float64(1), object(10)
memory usage: 509.6+ KB

Приведем признак runtime_clear в формат int с помощью метода astype()

In [35]:
dataset = dataset[dataset["runtime_clear"].notna()]

Проверим тип данных с помощью метода info()

In [36]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4970 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   poster         4970 non-null   object
 1   title          4970 non-null   object
 2   certificate    4970 non-null   object
 3   runtime        4970 non-null   object
 4   genre          4970 non-null   object
 5   rating         4970 non-null   float64
 6   about          4956 non-null   object
 7   director       4970 non-null   object
 8   stars          4970 non-null   object
 9   votes          4970 non-null   object
 10  gross_earn     4574 non-null   object
 11  runtime_clear  4970 non-null   Int64
dtypes: Int64(1), float64(1), object(10)
memory usage: 509.6+ KB

### *5.2. gross_earn*

По аналогии приведем признак gross_earn к числовому типу данных

Выведем Series ['gross_earn'] для детального просмотра данных

In [37]:
dataset['gross_earn']

0        $28.34M
1       $534.86M
2       $292.58M
3        $37.03M
4       $107.93M
          ...
4994         NaN
4995      $9.40M
4996         NaN
4998      $6.67M
4999      $8.20M
Name: gross_earn, Length: 4970, dtype: object

Напишем функцию, которая исключит нецифровые символы с помощью регулярных выражений. Подумаем, нужно ли оставлять при этом в них точку.

In [38]:
def clear_gross_earn(gross_earn):
    return re.sub(r'[^\d\.]', '', gross_earn)

Оценим количество пропущенных значений по признаку с помощью метода isna() в связке с методом sum()

In [39]:
dataset['gross_earn'].isna().sum()

np.int64(396)

Необходимо добавить в функцию обработку пустых значений. Для этого импортируем библиотеку numpy с коротким наименованием np

In [40]:
import numpy as np

Добавим в функцию проверку на пустые значения с помощью метода pandas pd.isna(). В случае пропуска она должна вернуть пустое значение np.nan; в ином случае - сохранить алгоритм, написанный ранее (переписывать функцию ниже не будем; просто изучим, как она работает)

In [41]:
def clear_gross_earn(gross_earn):
  if pd.isna(gross_earn):
    return np.nan
  else:
    return re.sub('[^\d\.]', '', gross_earn)

<>:5: SyntaxWarning: invalid escape sequence '\d'
<>:5: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_7998/1859203611.py:5: SyntaxWarning: invalid escape sequence '\d'
  return re.sub('[^\d\.]', '', gross_earn)

Примените функцию к Series ['gross_earn'] с помощью метода apply()

In [42]:
dataset['gross_earn'].apply(clear_gross_earn)

0        28.34
1       534.86
2       292.58
3        37.03
4       107.93
         ...
4994       NaN
4995      9.40
4996       NaN
4998      6.67
4999      8.20
Name: gross_earn, Length: 4970, dtype: object

Создадим столбец gross_earn в исходном датасете, применив функцию к признаку gross_earn

In [43]:
dataset['gross_earn_clear'] = dataset['gross_earn'].apply(clear_gross_earn)

Выведем Series ['gross_earn_clear'] для оценки результата

In [44]:
dataset['gross_earn_clear']

0        28.34
1       534.86
2       292.58
3        37.03
4       107.93
         ...
4994       NaN
4995      9.40
4996       NaN
4998      6.67
4999      8.20
Name: gross_earn_clear, Length: 4970, dtype: object

Приведем признак gross_earn_clear в формат float с помощью метода astype()

In [45]:
dataset['gross_earn_clear'] = dataset['gross_earn_clear'].astype(float)

Код был выполнен. Оценим результат, детально рассмотрев Series ['gross_earn_clear']

In [46]:
dataset['gross_earn_clear']

0        28.34
1       534.86
2       292.58
3        37.03
4       107.93
         ...
4994       NaN
4995      9.40
4996       NaN
4998      6.67
4999      8.20
Name: gross_earn_clear, Length: 4970, dtype: float64

Выведем информацию о датасете с помощью метода info()

In [47]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4970 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   poster            4970 non-null   object
 1   title             4970 non-null   object
 2   certificate       4970 non-null   object
 3   runtime           4970 non-null   object
 4   genre             4970 non-null   object
 5   rating            4970 non-null   float64
 6   about             4956 non-null   object
 7   director          4970 non-null   object
 8   stars             4970 non-null   object
 9   votes             4970 non-null   object
 10  gross_earn        4574 non-null   object
 11  runtime_clear     4970 non-null   Int64
 12  gross_earn_clear  4574 non-null   float64
dtypes: Int64(1), float64(2), object(10)
memory usage: 548.4+ KB

Все получилось: признаки runtime и gross_earn в числовом формате!

## 6. Сортировка по рейтингу

Отсортируем датасет в порядке убывания рейтинга фильмов (rating), применив метод sort_values() с переданным в него параметром ascending=False

In [48]:
sorted_dataset = dataset.sort_values(by='rating', ascending=False)
sorted_dataset.head()

,poster,title,certificate,runtime,genre,rating,about,director,stars,votes,gross_earn,runtime_clear,gross_earn_clear
0,https://m.media-amazon.com/images/S/sash/4Fyxw...,The Shawshank Redemption,15,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,"('Tim Robbins',), ('Morgan Freeman',), ('Bob G...","26,26,905",$28.34M,142,28.34
9,https://m.media-amazon.com/images/S/sash/4Fyxw...,The Godfather,X,175 min,"Crime, Drama",9.2,The aging patriarch of an organized crime dyna...,Francis Ford Coppola,"('Marlon Brando',), ('Al Pacino',), ('James Ca...","18,19,641",$134.97M,175,134.97
3788,https://m.media-amazon.com/images/S/sash/4Fyxw...,Hababam Sinifi,12A,87 min,"Comedy, Drama",9.2,"Lazy, uneducated students share a very close b...",Ertem Egilmez,"('Kemal Sunal',), ('Münir Özkul',), ('Halit Ak...","40,492",NaN,87,NaN
8,https://m.media-amazon.com/images/S/sash/4Fyxw...,The Lord of the Rings: The Return of the King,12A,201 min,"Action, Adventure, Drama",9.0,Gandalf and Aragorn lead the World of Men agai...,Peter Jackson,"('Elijah Wood',), ('Viggo Mortensen',), ('Ian ...","18,01,662",$377.85M,201,377.85
24,https://m.media-amazon.com/images/S/sash/4Fyxw...,Schindler's List,15,195 min,"Biography, Drama, History",9.0,"In German-occupied Poland during World War II,...",Steven Spielberg,"('Liam Neeson',), ('Ralph Fiennes',), ('Ben Ki...","13,33,407",$96.90M,195,96.90

## 7. Переопределение индексов

Переопределим индексы по порядку с помощью метода reset_index() с переданными в него параметрами drop=True для удаления предыдущего столбца индексов и inplace=True для автоматической перезаписи таблицы

In [49]:
sorted_dataset.reset_index(drop=True, inplace=True)
sorted_dataset.head()

,poster,title,certificate,runtime,genre,rating,about,director,stars,votes,gross_earn,runtime_clear,gross_earn_clear
0,https://m.media-amazon.com/images/S/sash/4Fyxw...,The Shawshank Redemption,15,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,"('Tim Robbins',), ('Morgan Freeman',), ('Bob G...","26,26,905",$28.34M,142,28.34
1,https://m.media-amazon.com/images/S/sash/4Fyxw...,The Godfather,X,175 min,"Crime, Drama",9.2,The aging patriarch of an organized crime dyna...,Francis Ford Coppola,"('Marlon Brando',), ('Al Pacino',), ('James Ca...","18,19,641",$134.97M,175,134.97
2,https://m.media-amazon.com/images/S/sash/4Fyxw...,Hababam Sinifi,12A,87 min,"Comedy, Drama",9.2,"Lazy, uneducated students share a very close b...",Ertem Egilmez,"('Kemal Sunal',), ('Münir Özkul',), ('Halit Ak...","40,492",NaN,87,NaN
3,https://m.media-amazon.com/images/S/sash/4Fyxw...,The Lord of the Rings: The Return of the King,12A,201 min,"Action, Adventure, Drama",9.0,Gandalf and Aragorn lead the World of Men agai...,Peter Jackson,"('Elijah Wood',), ('Viggo Mortensen',), ('Ian ...","18,01,662",$377.85M,201,377.85
4,https://m.media-amazon.com/images/S/sash/4Fyxw...,Schindler's List,15,195 min,"Biography, Drama, History",9.0,"In German-occupied Poland during World War II,...",Steven Spielberg,"('Liam Neeson',), ('Ralph Fiennes',), ('Ben Ki...","13,33,407",$96.90M,195,96.90

## 8. Сохранение датасета

Сохраним датасет под названием movies_clean в формате csv и при необходимости сохраним его локально. Он понадобится нам при дальнейшем разведочном анализе

In [50]:
sorted_dataset.to_excel('movies_clean.xlsx', index=False)

In [51]:
sorted_dataset.to_csv('movies_clean.csv')